<<<<<<< HEAD
#testing

name: Deploy to AWS
=======
name: Terraform AWS Provisioning
>>>>>>> 6466731 (modified tf files for Github action deployment)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to true to destroy resources'
        required: false
        default: 'false'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
         role-to-assume: arn:aws:iam::457082365292:role/githuoidc
         aws-region: eu-west-2

      - name: ðŸ§° Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

<<<<<<< HEAD

          
=======
      - name: âš™ï¸ Terraform Init
        run: terraform init

      - name: ðŸ“Š Terraform Plan
        run: terraform plan -input=false -out=tfplan

     # - name: ðŸš€ Terraform Apply (main branch only)
     #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
     #   run: terraform apply -auto-approve tfplan

    #  - name: ðŸ’£ Terraform Destroy (manual trigger)
     #   if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true'
    #    run: terraform destroy -auto-approve
>>>>>>> 6466731 (modified tf files for Github action deployment)
