name: Terraform Kubernetes Provisioner

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to true to destroy resources'
        required: true
        default: 'false'

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: ğŸ§° Setup Terraform
#        uses: hashicorp/setup-terraform@v2
#        with:
#          terraform_version: 1.6.0

#       # Install AWS CLI v2. 
#      - name: Install AWS CLI
#        run: |
#          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#          unzip awscliv2.zip
#          sudo ./aws/install --update
#          aws --version
#          aws sts get-caller-identity

      - uses: actions/github-script@v8
        id: script
        timeout-minutes: 10
        with:
          debug: true
          script: |
            const token = process.env['ACTIONS_ID_TOKEN_REQUEST_TOKEN']
            const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
            core.setOutput('TOKEN', token.trim())
            core.setOutput('IDTOKENURL', runtimeUrl.trim())

      # Fetch OIDC JWT with correct audience and extract value
      - name: Fetch OIDC JWT
        id: jwt
        run: |
          OIDC_JWT=$(curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}?audience=sts.amazonaws.com" \
            | jq -r '.value')

          echo "OIDC_JWT=$OIDC_JWT" >> $GITHUB_ENV
          echo $OIDC_JWT | cut -d. -f2 | base64 -d | jq .

      # Exchange JWT for AWS credentials
      - name: Assume AWS Role
        run: |
          CREDS=$(aws sts assume-role-with-web-identity \
            --role-arn arn:aws:iam::457082365292:role/Github-action \
            --role-session-name gh-actions-oidc \
            --web-identity-token "$OIDC_JWT" \
            --duration-seconds 3600)

          echo "AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV

      # Run Terraform
      - name: Terraform Init
        run: terraform init



        

   #   - name: ğŸ“Š Terraform Plan
    #    run: terraform plan -input=false -out=tfplan



  #    - name: ğŸš€ Terraform Apply (main branch only)
  #     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #     run: terraform apply -auto-approve
        

#      - name: ğŸ’£ Terraform Destroy (manual trigger)
#        if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true'
#        run: terraform destroy -auto-approve
