name: Terraform kubernetes Provisioning

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to true to destroy resources'
        required: true
        default: 'false'


permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ğŸ§° Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

       # Install AWS CLI v2. 
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      # Fetch OIDC JWT manually
      - name: Fetch OIDC JWT
        id: jwt
        run: |
          curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}?audience=sts.amazonaws.com" \
            > /tmp/id-token.json
          echo "OIDC_JWT=$(jq -r '.value' /tmp/id-token.json)" >> $GITHUB_ENV

      # Exchange JWT for AWS credentials
      - name: Assume AWS Role
        run: |
          CREDS=$(aws sts assume-role-with-web-identity \
            --role-arn arn:aws:iam::457082365292:role/Github-action \
            --role-session-name gh-actions-oidc \
            --web-identity-token "$OIDC_JWT" \
            --duration-seconds 3600)

          echo "AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV
          echo $OIDC_JWT | cut -d. -f2 | base64 -d | jq .

      # Run Terraform
      - name: âš™ï¸ Terraform Init
        run: |
           terraform init
        

      - name: ğŸ“Š Terraform Plan
        run: terraform plan -input=false -out=tfplan



  #    - name: ğŸš€ Terraform Apply (main branch only)
  #     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #     run: terraform apply -auto-approve
        

#      - name: ğŸ’£ Terraform Destroy (manual trigger)
#        if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true'
#        run: terraform destroy -auto-approve
